server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/public; # Мы будем хранить публичные файлы в папке public
    client_max_body_size 10M; # Максимальный размер загружаемого файла

    location /storage/ {
        return 404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass foodtracker-app:9000; # Имя сервиса из docker-compose
        fastcgi_connect_timeout 10s;
        fastcgi_send_timeout 75s;
        fastcgi_read_timeout 75s;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
