name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy production  to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy production over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/foodtracker
            ./deploy.sh
